export {
	FLIGHT_DURATION_MS,
	COLLISION_PADDING_DEGREES,
	DEFAULT_COLLISION_CONFIG,
	signedAngularSpeedDegreesPerSecond,
	targetAngleAtElapsed,
	localImpactAngleAtElapsed,
	computeMinAngularSeparationDegrees,
	collisionConfigForLevel,
	createInitialGameState,
	resetGameState,
	tryBeginThrow,
	resolveThrowImpact,
	advanceTargetAngle,
} from './gameEngine'
